hydra:
  run:
    dir: logdir/${algo}/${env_id}/${exp_id}/${seed}

algo: "dispo_ultrafast_test"
seed: 0
env_id: "antmaze-medium-diverse-v2"
exp_id: "ultrafast_test"
logdir: ${hydra:run.dir}
gamma: 0.99
reward_min: 0
reward_max: 1
num_reward_samples: 500

feat:
  type: "fourier"
  dim: 16  # Very small

training:
  num_steps: 500   # Very small
  eval_every: 5000 # No evaluation during training (higher than num_steps)
  save_every: 5000 # No saving during training
  batch_size: 32
  num_workers: 1
  resume: False
  log_psi_video: False
  weighted_regression: False
  
model:
  embed_dim: 32    # Very small
  embed_type: "positional"
  ema_rate: 0.995
  lr: 3e-4
  wd: 1e-6
  warmup_steps: 5
  sde: "vpsde"
  beta_min: 0.1
  beta_max: 20
  num_steps: 50    # Very small
  continuous: False
  
  # ValueDecoder configuration (minimal)
  task_embedding_dim: 4
  value_hidden_dims: [32, 16]
  value_dropout: 0.0  # No dropout for speed

sampling:
  predictor: "ddim"
  corrector: "none"
  n_inference_steps: 3  # Very small
  eta: 0.0

planning:
  planner: "random_shooting"
  guidance_coef: 1.0
  num_samples: 3   # Minimal sampling
  num_elites: 1

eval:
  num_episodes: 1